name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ✅ Install dependencies for both backend & frontend
      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      # ✅ Run Backend tests
      - name: Run Backend Tests (Without Starting Server)
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          cd backend
          npm test -- --coverage  # ✅ Directly run tests (without starting `server.js`)

      # ✅ Run Backend Tests (Unit + Integration)
      - name: Run backend tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: cd backend && npm test -- --coverage

      # ✅ Run Frontend Tests (Ensuring Backend is Running)
      - name: Run frontend tests
        run: cd frontend && npm test -- --coverage

      # ✅ Upload Coverage Reports as Artifacts
      - name: Upload test coverage reports
        uses: actions/upload-artifact@v4 # ✅ Updated to v4
        with:
          name: coverage-reports
          path: |
            backend/coverage
            frontend/coverage
          retention-days: 7 # Keep artifacts for 7 days
