name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      # ✅ Step 1: Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Step 2: Set Up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ✅ Step 3: Install Dependencies
      - name: Install dependencies (Backend & Frontend)
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      # ✅ Step 4: Run Backend Tests (With Coverage)
      - name: Run Backend Tests (Unit & Integration)
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          cd backend
          npm test -- --coverage  # ✅ Runs all backend tests

      # ✅ Step 5: Run Frontend Tests (With Coverage)
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --coverage

      # ✅ Step 6: Upload Coverage Reports as Artifacts
      - name: Upload test coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            backend/coverage
            frontend/coverage
          retention-days: 7 # Keep artifacts for 7 days
